# Generated by Django 3.0.5 on 2020-06-16 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pixkal2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='GPS', max_length=200)),
                ('titulo', models.CharField(default='Avatar', max_length=100)),
                ('model_3DName', models.CharField(max_length=200)),
                ('model_Image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_busqueda', models.CharField(max_length=350)),
                ('recompensa', models.CharField(max_length=200)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(default='', max_length=350)),
                ('numero_personas', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('I', 'Inactivo'), ('C', 'Cancelado'), ('A', 'Activo'), ('T', 'Terminado')], max_length=1)),
                ('no_items', models.PositiveSmallIntegerField(default=0)),
                ('imagen', models.ImageField(default='', upload_to=pixkal2.models.upload_location_busqueda, validators=[pixkal2.models.validate_image])),
                ('creador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusquedaLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pregunta', models.TextField(default='', max_length=350)),
                ('respuesta', models.CharField(default='', max_length=20)),
                ('bandera_pregunta', models.SmallIntegerField(default=0)),
                ('sonido', models.FileField(default='', upload_to=pixkal2.models.upload_location_treasure_s, validators=[pixkal2.models.validate_image])),
                ('bandera_sonido', models.SmallIntegerField(default=0)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Avatar')),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Busqueda')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=350)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(default='', upload_to=pixkal2.models.upload_location_clase, validators=[pixkal2.models.validate_image])),
                ('no_items', models.PositiveSmallIntegerField(default=0)),
                ('bandera_marcador', models.CharField(choices=[('M', 'Utilizar marcador'), ('S', 'Sin marcador')], default='M', max_length=1)),
                ('estado', models.CharField(choices=[('I', 'Inactivo'), ('C', 'Cancelado'), ('A', 'Activo'), ('T', 'Terminado')], default='I', max_length=1)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_busqueda', models.ImageField(upload_to=pixkal2.models.upload_location, validators=[pixkal2.models.validate_image])),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Avatar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEncontrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Busqueda')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.BusquedaLugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('B', 'Búsqueda'), ('C', 'Clase'), ('S', 'Stream')], default='M', max_length=1)),
                ('titulo', models.CharField(max_length=350)),
                ('descripcion', models.TextField(default='', max_length=350)),
                ('imagen', models.CharField(max_length=350)),
                ('url', models.CharField(max_length=350)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonido', models.FileField(default='', upload_to=pixkal2.models.upload_location_c, validators=[pixkal2.models.validate_image])),
                ('bandera_sonido', models.SmallIntegerField(default=0)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Avatar')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Perfil'),
        ),
        migrations.AddField(
            model_name='clase',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Question')),
            ],
        ),
        migrations.CreateModel(
            name='BusquedaParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_encontrados', models.SmallIntegerField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Activo'), ('G', 'Ganador'), ('T', 'Terminado')], max_length=1)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Busqueda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='busqueda',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Perfil'),
        ),
    ]
