# Generated by Django 3.0.5 on 2020-04-28 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pixkal2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_busqueda', models.CharField(max_length=350)),
                ('recompensa', models.CharField(max_length=200)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('numero_personas', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('I', 'Inactivo'), ('C', 'Cancelado'), ('A', 'Activo'), ('T', 'Terminado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BusquedaParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_encontrados', models.SmallIntegerField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Activo'), ('G', 'Ganador'), ('T', 'Terminado')], max_length=1)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Busqueda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusquedaLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Avatar')),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Busqueda')),
            ],
        ),
    ]
