# Generated by Django 3.0.5 on 2020-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0003_dash_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(default='', max_length=350),
        ),
    ]
