# Generated by Django 3.0.5 on 2020-05-02 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pixkal2', '0003_auto_20200430_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEncontrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Busqueda')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.BusquedaLugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
