# Generated by Django 3.0.5 on 2020-06-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0004_clase_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
