# Generated by Django 3.0.5 on 2020-05-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0004_itemencontrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='tipo',
            field=models.CharField(default='GPS', max_length=200),
        ),
    ]
