# Generated by Django 3.0.5 on 2020-05-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0005_avatar_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='descripcion',
            field=models.TextField(default='Lorem Ipsum', max_length=350),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='duracion',
            field=models.CharField(choices=[('0', 'Sin limite de tiempo'), ('10', '10 min.'), ('20', '20 min.'), ('30', '30 min.'), ('60', '60 min.'), ('120', '120 min.'), ('180', '180 min.')], default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='imagen',
            field=models.ImageField(default='default.jpg', height_field=50, upload_to='', width_field=50),
        ),
        migrations.AlterField(
            model_name='busqueda',
            name='creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='busqueda',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='busqueda',
            name='inicio',
            field=models.DateField(),
        ),
    ]
