# Generated by Django 3.0.5 on 2020-06-22 22:28

from django.db import migrations, models
import pixkal2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0005_auto_20200618_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='contador_usuarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='contador_visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clase',
            name='bandera_foco',
            field=models.CharField(choices=[('L', 'Libre'), ('F', 'Mirar de frente')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='clase',
            name='contador_usuarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clase',
            name='contador_visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claseitem',
            name='bandera_avatar',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claseitem',
            name='item',
            field=models.FileField(default='', upload_to=pixkal2.models.upload_location_a, validators=[pixkal2.models.validate_image]),
        ),
        migrations.AddField(
            model_name='claseitem',
            name='tipo',
            field=models.CharField(choices=[('A', 'Avatar'), ('V', 'Video'), ('I', 'Imagen')], default='A', max_length=1),
        ),
    ]
