# Generated by Django 3.0.5 on 2020-05-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0006_auto_20200516_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='imagen',
            field=models.ImageField(default='default.jpg', height_field='50', upload_to='', width_field='50'),
        ),
    ]
