# Generated by Django 3.0.5 on 2020-05-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0007_auto_20200516_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busqueda',
            name='imagen',
        ),
    ]
