# Generated by Django 3.0.5 on 2020-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0009_avatar_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='descripcion',
            field=models.TextField(default='', max_length=350),
        ),
    ]
