# Generated by Django 3.0.5 on 2020-06-05 18:19

from django.db import migrations, models
import django.db.models.deletion
import pixkal2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0013_auto_20200604_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='imagen',
            field=models.ImageField(default='', upload_to=pixkal2.models.upload_location_busqueda),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Perfil'),
        ),
        migrations.AddField(
            model_name='clase',
            name='imagen',
            field=models.ImageField(default='', upload_to=pixkal2.models.upload_location_clase),
        ),
        migrations.AddField(
            model_name='clase',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Perfil'),
        ),
    ]
