# Generated by Django 3.0.5 on 2020-06-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0014_auto_20200605_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedalugar',
            name='bandera_pregunta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busquedalugar',
            name='pregunta',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='busquedalugar',
            name='respuesta',
            field=models.CharField(default='', max_length=20),
        ),
    ]
