# Generated by Django 3.0.5 on 2020-06-07 02:38

from django.db import migrations, models
import pixkal2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0015_auto_20200606_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busqueda',
            name='imagen',
            field=models.ImageField(default='', upload_to=pixkal2.models.upload_location_busqueda, validators=[pixkal2.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='clase',
            name='imagen',
            field=models.ImageField(default='', upload_to=pixkal2.models.upload_location_clase, validators=[pixkal2.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen_busqueda',
            field=models.ImageField(upload_to=pixkal2.models.upload_location, validators=[pixkal2.models.validate_image]),
        ),
    ]
