# Generated by Django 3.0.5 on 2020-06-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0016_auto_20200606_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busqueda',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='busqueda',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='busqueda',
            name='inicio',
        ),
    ]
