# Generated by Django 3.0.5 on 2020-06-10 22:47

from django.db import migrations, models
import pixkal2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0017_auto_20200610_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedalugar',
            name='sonido',
            field=models.FileField(default='', upload_to=pixkal2.models.upload_location_treasure_s, validators=[pixkal2.models.validate_image]),
        ),
    ]
