# Generated by Django 3.0.5 on 2020-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0018_busquedalugar_sonido'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedalugar',
            name='bandera_sonido',
            field=models.SmallIntegerField(default=0),
        ),
    ]
