# Generated by Django 3.0.5 on 2020-06-13 19:02

from django.db import migrations, models
import django.db.models.deletion
import pixkal2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0019_busquedalugar_bandera_sonido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonido', models.FileField(default='', upload_to=pixkal2.models.upload_location_treasure_s, validators=[pixkal2.models.validate_image])),
                ('bandera_sonido', models.SmallIntegerField(default=0)),
                ('bandera_marcador', models.SmallIntegerField(default=0)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Avatar')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixkal2.Clase')),
            ],
        ),
    ]
