# Generated by Django 3.0.5 on 2020-06-13 19:27

from django.db import migrations, models
import pixkal2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixkal2', '0020_claseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('I', 'Inactivo'), ('C', 'Cancelado'), ('A', 'Activo'), ('T', 'Terminado')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='clase',
            name='no_items',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='claseitem',
            name='sonido',
            field=models.FileField(default='', upload_to=pixkal2.models.upload_location_c, validators=[pixkal2.models.validate_image]),
        ),
    ]
